version: '2.1'

services:
  python-sample-vscode-django-tutorial:
    image: python-sample-vscode-django-tutorial
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
